require("plenary.async").tests.add_to_env()
local reflection = require("libp.debug.reflection")
local auv = require("libp.fs.uv_async")

describe("__index", function()
    it("Gets vim.loop function when not defined", function()
        assert.are.equal(vim.loop.read_start, auv.read_start)
    end)
    it("Gets uv_async function when it's defined", function()
        assert.are_not.equal(vim.loop.read_start, auv.fs_open)
    end)
end)

a.describe("add", function()
    a.it("Swap the return values for async libuv callback", function()
        local res, err = auv.fs_opendir(reflection.script_dir())
        assert.is_truthy(res)
        assert.is_falsy(err)
        auv.fs_closedir(res)

        res, err = auv.fs_opendir("no_such_dir")
        assert.is_falsy(res)
        assert.is_truthy(err)
    end)
end)
