local itertools = require("libp.datatype.itertools")

describe("from_range", function()
    it("Defaults with step 1", function()
        assert.are.same({ 1, 2, 3, 4 }, itertools.range(1, 4):collect())
    end)
    it("Supports customized step", function()
        assert.are.same({ 1, 3 }, itertools.range(1, 4, 2):collect())
        assert.are.same({ 1, 3, 5 }, itertools.range(1, 5, 2):collect())
    end)
    it("Can go from high to low", function()
        assert.are.same({ 4, 2 }, itertools.range(4, 1, -2):collect())
        assert.are.same({ 5, 3, 1 }, itertools.range(5, 1, -2):collect())
    end)
end)
