local args = require("libp.utils.args")
describe("get_default", function()
    it("Returns default if val is nil", function()
        assert.are.same(1, args.get_default(nil, 1))
        assert.are.same(false, args.get_default(nil, false))
    end)
    it("Returns val if val is not nil", function()
        assert.are.same(2, args.get_default(2, 3))
        assert.are.same(false, args.get_default(false, 3))
    end)
end)
