local mathfn = require("libp.utils.mathfn")

describe("decimal_to_octal", function()
    it("Converts decimal to octal", function()
        assert.are.same(1, mathfn.decimal_to_octal(1))
        assert.are.same(2, mathfn.decimal_to_octal(2))
        assert.are.same(3, mathfn.decimal_to_octal(3))
        assert.are.same(4, mathfn.decimal_to_octal(4))
        assert.are.same(5, mathfn.decimal_to_octal(5))
        assert.are.same(6, mathfn.decimal_to_octal(6))
        assert.are.same(7, mathfn.decimal_to_octal(7))
        assert.are.same(10, mathfn.decimal_to_octal(8))
        assert.are.same(11, mathfn.decimal_to_octal(9))
        assert.are.same(12, mathfn.decimal_to_octal(10))
        assert.are.same(13, mathfn.decimal_to_octal(11))
        assert.are.same(14, mathfn.decimal_to_octal(12))
        assert.are.same(15, mathfn.decimal_to_octal(13))
        assert.are.same(16, mathfn.decimal_to_octal(14))
        assert.are.same(17, mathfn.decimal_to_octal(15))
        assert.are.same(20, mathfn.decimal_to_octal(16))
    end)
end)
