local ProgressWindow = require("libp.ui.ProgressWindow")
local styles = require("libp.ui.progressbar_style")
local test_style = "clock"
local style_with_two_element = "toggle7"

describe("tick", function()
    describe("total is known", function()
        it("Defaults to no desc", function()
            local p = ProgressWindow({ total = 10 })
            p:open()
            p:tick(0)
            assert.are.same({ "" }, p.buffer:get_lines())
            p:tick(1)
            assert.is_true(vim.startswith(p.buffer:get_line(1), "█"))
        end)
        it("Respects input desc", function()
            local p = ProgressWindow({ desc = "Desc:", total = 10 })
            p:open()
            p:tick(0)
            assert.are.same({ "Desc:" }, p.buffer:get_lines())
            p:tick(1)
            assert.is_true(vim.startswith(p.buffer:get_line(1), "Desc:█"))
        end)
        it("Automatically close when reaching total", function()
            local p = ProgressWindow({ desc = "Desc:", total = 10 })
            p:open()
            assert.is_true(vim.api.nvim_win_is_valid(p.id))
            p:tick(10)
            assert.is_false(vim.api.nvim_win_is_valid(p.id))
        end)
    end)

    describe("total is unknown", function()
        it("Defaults to no desc", function()
            local p = ProgressWindow({ style = test_style })
            p:open()
            p:tick(0)
            assert.are.same({ styles[test_style][1] }, p.buffer:get_lines())
            p:tick(1)
            assert.are.same({ styles[test_style][2] }, p.buffer:get_lines())
            p:close()
        end)
        it("Respects input desc", function()
            local p = ProgressWindow({ desc = "Desc:", style = test_style })
            p:open()
            p:tick(0)
            assert.are.same({ "Desc:" .. styles[test_style][1] }, p.buffer:get_lines())
            p:tick(1)
            assert.are.same({ "Desc:" .. styles[test_style][2] }, p.buffer:get_lines())
            p:close()
        end)
        it("Wraps around style array", function()
            local p = ProgressWindow({ style = style_with_two_element })
            p:open()
            p:tick(0)
            assert.are.same({ styles[style_with_two_element][1] }, p.buffer:get_lines())
            p:tick(1)
            assert.are.same({ styles[style_with_two_element][2] }, p.buffer:get_lines())
            p:tick(1)
            assert.are.same({ styles[style_with_two_element][1] }, p.buffer:get_lines())
            p:close()
        end)
    end)
end)
