---@brief [[
---Do not edit this file, it was generated!
---Provides a function that partial binds arguments to a lua function.
---@brief ]]

return {
{% for n in range(1, amount) %}
function (fn {% for n in range(n) %} , A{{n+1}} {% endfor %})
		return function(...)
			return fn({% for n in range(n) %} A{{n+1}} {{ ", " if not loop.last else "" }} {% endfor %}, ...)
		end
	end,
{% endfor %}
}
